### ISSUE TITLE
Rename extension to "mysqlreport"

### ISSUE THREAD

**Issue by mblaschke** [froemken/sfmysqlreport#6]
Damit die Extension als generelle Extension wirkt und nicht nur als Firmen- bzw. Persoenliche Extension, so dass der Anreiz fuers Contributen groesser wird :)

**Comment by froemken** [comment]
I will do it. But not jet. Many people get this link just right now. Give me a week or two.

**Comment by mblaschke** [comment]
:+1:

**Comment by kairichter** [comment]
Extension key is registered on typo3.org and transferred to you ;-)

**Comment by froemken** [comment]
Thank you. I just have uploaded version 0.3.0 to TER. It should work with TYPO3 6.2 until current master. I will delete this repository within the next time
